### PR TITLE
Update streamruby.py

### PR DESCRIPTION
**Pull request by bassemhelal18**

### CODE REVIEW

**Comment by shellc0de27** [comment]
This regex is incorrect and should not have been merged. @bassemhelal18 You know there is no shame is raising an issue when you don't have a clue what you're doing. This seems to be a recurring thing now for whatever reason.

@Gujal00 i might fix this later as i do have another domain to add too

**Comment by Gujal00** [comment]
hmm, i didn't look deeply before merging, sorry about that, i was about to release an update and this PR came up so merged it without much thought :(

**Comment by shellc0de27** [comment]
@Gujal00 All good man shit happens :) It only affected the domain ext. Which included things like host,  the referer, etc. but still resolved i believe.
I'm more concerned that others (One person in particular) are not taking the extra time to the basics like double checking your work and testing before committing code to a public repo that thousands of others rely on and use on a daily basis.

**Comment by bassemhelal18** [comment]
Sorry my mistake @Gujal00 

@shellc0de27 i think you like to talk a lot instead you can just edit the file and do it but I as told you you like to talk so keep talking 😅

**Comment by shellc0de27** [comment]
@bassemhelal18 LMAO your so-called pull requests prove my point. Have a look 🤡

**Comment by bassemhelal18** [comment]
@shellc0de27 do you like to send you again a screenshot where to find edit the file 🤣🤣🤣

**Comment by shellc0de27** [comment]
@bassemhelal18 So what you are saying, you expect us (the people who can actually code) to fix your mistakes. The same ones you been making since the beginning of the year?

**Comment by bassemhelal18** [comment]
Come on man be respectful you can check when @Gujal00 find a mistake 
He can said there is a mistake fix it or he fix it we are here helping each other so when you find a mistake you can just be respectful.

**Comment by shellc0de27** [comment]
lol oh did i hit a nerve? Clearly you are the one that needs help. You can't even copy n paste correctly, I'm not here to help you, you can't even help yourself.

Like i told you before, you can't code...so raise a damn issue!

**Comment by bassemhelal18** [comment]
I was trying to be respectful with you but I think you can't understand I didn't ask for your help and I think it's @Gujal00 call not yours 
So as I told you before keep talking

**Comment by shellc0de27** [comment]
Dude you just told me all i have to do is edit the file. Which you are implying that WE have to keep fixing YOUR mistakes as if you don't give a shit. I have a big problem with that.
What is gujal's call? The regex was clearing wrong in this pull request.

**Comment by Gujal00** [comment]
Guys we are all human and are prone to mistakes sometimes.
we do this for fun, just leave it at that

**Comment by Gujal00** [comment]
@shellc0de27 
> i might fix this later as i do have another domain to add too

Do you want to add that domain or should I release smr with the streamruby fix? Thanks

**Comment by shellc0de27** [comment]
@Gujal00 Yeah you can release if you want too. Sorry just been really busy and not sure yet when i will have the extra time. Thanks though

**Pull request merged**
