### PR TITLE
Update filemoon resolver

### PR DESCRIPTION
**Pull request by vargalex**
Filemoon started to use iframe in html, so we need to download the iframe src

### CODE REVIEW

**Comment by Gujal00** [comment]
I did it slightly differently in https://github.com/Gujal00/ResolveURL/commit/496d2b914c8164ce75e899765de7eb8bd10b580a
Can you please check if it works for you?

**Comment by vargalex** [comment]
Of course, it works, the codes are practically identical. You have simplifies the code (I have 1 unnecessary if). Sould I close the pull request, or you close it?

**Comment by Gujal00** [comment]
> Of course, it works, the codes are practically identical. You have simplifies the code (I have 1 unnecessary if). Should I close the pull request, or close it you?

The issue with your PR was that in case of iframe url, the final url should have the iframe url as referrer and origin. This was missing in your code which I added in mine

**Comment by vargalex** [comment]
> If i recall re.search does the check itself and returns None if it doesnt find the content so your first if line isnt needed vargalex. (Sayin so for future reference.) Also id go ahead and just close it yourself incase gujal is busy, he will likely see your response when he gets back on here.

I wrote the same: "I have 1 unnecessary if". I mean this code:
`if 'iframe src' in html:`

**Comment by vargalex** [comment]
> > Of course, it works, the codes are practically identical. You have simplifies the code (I have 1 unnecessary if). Should I close the pull request, or close it you?
> 
> The issue with your PR was that in case of iframe url, the final url should have the iframe url as referrer and origin. This was missing in your code which I added in mine

OK, I forgot to set the web_url variable. It is possible, that by some URL this is necessary, but with URLs I tested, that was not a problem. Thanks for the fix!

**Pull request closed without merging**
