### PR TITLE
Update clicknupload.py

### PR DESCRIPTION
**Pull request by jewbmx**
alternate domains added/updated to. altho im not sure if the resolver still works, my links gave a unable to find file error lol

### CODE REVIEW

**Comment by shellc0de27** [comment]
Hey @jewbmx , Yeah its been broken for some time. Forget the reason why @Gujal00 said we're not able to resolve it anymore as i have not looked at it since and never bothered updating the domains either cause i thought it was pointless unless we can fix the resolver.

**Comment by Gujal00** [comment]
Thanks

**Comment by shellc0de27** [comment]
@Gujal00 is this resolver working now?

**Comment by Gujal00** [comment]
The url that gets resolved by resolveurl is corrrect and if pasted on a browser (no need for any headers) downloads the file. But does not work on kodi videoplayer, unfortunately.
If you enable debug in kodi and enable component level debugging for curl and ffmpeg, you can see that curl is opening the file correctly and the first request goes with a header of `HEADER_OUT: Range: bytes=0-` and the response comes correctly back with `HEADER_IN: Content-Range: bytes 0-427377554/427377555`.
But then Kodi requests with `HEADER_OUT: Range: bytes=427246483-` which is the last byte and gets a `EOF` correctly and stops playback. No idea why Kodi requests the last byte, may be a bug in Kodi FFMPEG

**Comment by shellc0de27** [comment]
oh i see, thanks for the info :)

**Comment by jewbmx** [comment]
Sorry for a slow reply, somehow i didnt get notified lol.
Im not really sure if i ever seen this host or used it but when i seen the new domains in my scraper tests i decided to go ahead and update some like this just in case. I find it easier to stay up to date with sites by keeping the domains around incase things ever change tho so it wouldnt matter to me.

**Pull request merged**
