### PR TITLE
Update dembed additional domain

### PR DESCRIPTION
**Pull request by cywteow**
```
https://gotaku1.com/embedplus?id=MjA4MTg0&token=qtuYBUGdAP_tXBHJcp9yhA&expires=1689407229
https://gotaku1.com/streaming.php?id=MjA4MTg0&title=Uma+Musume%3A+Pretty+Derby+-+Road+to+the+Top+Episode+4
```

### CODE REVIEW

**Comment by shellc0de27** [comment]
This domain has been supported for almost the last 2 months in GoLoad

**Comment by cywteow** [comment]
> @cywteow @Gujal00 This domain has been supported for almost the last 2 months in GoLoad

weird, it wasn't working in the previous one.

**Comment by shellc0de27** [comment]
@cywteow I ran that url through smr tester and it resolved perfect. I would suggest you do the same. If still wont play, provide the output from the tester here and maybe some more info.

**Comment by Gujal00** [comment]
@shellc0de27 thanks for alerting, yes that domain did feel familiar but i didn't think twice when the PR came from @cywteow :)
I will revert the merge as it does work with goload resolver.
Thanks

**Pull request merged**
