### PR TITLE
Add border movement wrap-around functionality to captcha window

### PR DESCRIPTION
**Pull request by MrDini123**
Hey,

I was bothered that the play button is sometimes on the complete other side of the area where my red border marker is, so I added a feature that makes the border jump on the opposite side of the current movement.

I also wanted to dedupe the code reusal so I united the two action handlers. My approach could be problematic if some action has the same ID as a control I handle or vice-versa, but I haven't encountered such a case. In case if you want to be extra careful, the code can be modified so that we introduce an is_control boolean and handle the action depending on that bool separately. But that also adds a lot of extra statements...

Either way I ticked the allow edits by maintainers button on this PR, so feel free to adjust this to your needs. I am open to ideas.

### CODE REVIEW

**Comment by MrDini123** [comment]
@Gujal00 I noticed that you recently pushed on the repo. May I grab your attention on this? :relaxed:

**Comment by Gujal00** [comment]
Thanks for this, will certainly take a look, As this is an enhancement rather than a fix, didnt want to rush in during the holiday period :)

**Comment by MrDini123** [comment]
Fair enough, take your time and sorry for rushing! I was wondering if you just skipped it by accident. Frankly I can't find my way around the new Github UI and it hides the PR tab for me fully... :relaxed:

**Comment by Gujal00** [comment]
Thanks for the contribution

**Pull request merged**
