### PR TITLE
Update youdbox.py

### PR DESCRIPTION
**Pull request by bassemhelal18**

### CODE REVIEW

**Comment by shellc0de27** [comment]
@bassemhelal18 I'm scratching my head on this pull request, why are you making these changes? Domain is not valid and is for sale. On top of that, all the other code is not needed.

**Comment by Gujal00** [comment]
Exactly youdboox.site doesn't exist
https://www.nslookup.io/domains/youdboox.site/dns-records/ comes up empty, and all the other code is already part of generic resolver and not needed.

**Comment by shellc0de27** [comment]
@Gujal00 I don't think that's the case though. Don't think anyone has owned that domain, especially not youdbox. @bassemhelal18 where did you find this domain from?

**Comment by bassemhelal18** [comment]
A website use this domain but only working when I use youdbox.com sure am not adding it if I don't use it 😅

**Comment by shellc0de27** [comment]
@bassemhelal18  what's the website that is using the `youdboox.site` domain?

**Comment by bassemhelal18** [comment]
'https://daac17.dramacafe-tv.biz/watch.php?vid=2a54a9970'

Sorry but is there a problem to add this domain I think it will not affect anything 🤔

**Comment by shellc0de27** [comment]
I'm not seeing that domain anywhere on that site. Well you can't just add random domains to our resolvers, i do have a problem with that. Seeing that you don't code in python, regex, and dont know what you're doing.....yeah im going to question it.

**Comment by bassemhelal18** [comment]
image

**Comment by shellc0de27** [comment]
Thanks yes i see it. Its probably a mistype from the dumbass who runs that site. And is losing cash too lol. Stuff like should be handled addon side (your scraper) and not in SMR Cause im pretty sure youdbox never owned it. Guess its @Gujal00 call though

**Comment by Gujal00** [comment]
Okay, I did it slightly differently in https://github.com/Gujal00/ResolveURL/commit/ea984575a449432c0000d317aba97f12ea7f53fb
It is resolving correctly as below
`SMR Link Tester: Link Resolved: |https://youdboox.site/embed-o3zu07rm3vw2.html|https://psd1.youdbox.site/d/jcw2xxlqxm3qv3jsvopn434zpcdllnj74tzclvdyxjtaobg5sfncvpegqcshrcg4r2i2ktbz/video.mp4|User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+17.1.2%29+AppleWebKit%2F800.6.25+%28KHTML%2C+like+Gecko%29+Version%2F17.2+Safari%2F605.1.15&Referer=https%3A%2F%2Fyoudbox.site%2F&Origin=https%3A%2F%2Fyoudbox.site|`
@bassemhelal18 if it works fine for you in your testing, please close this PR. Thanks

**Pull request closed without merging**
