### PR TITLE
Mycloud key update

### PR DESCRIPTION
**Pull request by shellc0de27**

### CODE REVIEW

**Comment by Gujal00** [comment]
Thanks

**Comment by Gujal00** [comment]
Looks like they changed the key again and now gone full anti debug mode javascript. would be hard to debug that now

**Comment by sudovijay** [comment]
here - `wwQ91Q1S7L91ov5N`

for `scripts.js?v=1654570810`

**Comment by sudovijay** [comment]
Another change -` ?v=1654592409` - `RTorhhm9RwQwUjOi`

**Comment by Gujal00** [comment]
oh wow, they changed the key 4 times in a day. Thanks @sudovijay for working on this.
Looks like they have changed yet again `scripts.js?v=1654635614`

**Comment by sudovijay** [comment]
its def weird! extracted the code which converts it to series of numbers. they changing the script a lot (prolly after certain interval)

`?v=1654646410 cwVDurdp58ZLfFP0 &key=Q1nbJDsdM2BpgXNU`

```
 var crCode = customrc4key.charCodeAt(loopIndex);

 var arry = [];

  loopIndex % 6 == 0 ? crCode ^= 2 
   : loopIndex % 6 == 1 ? crCode *= 5
   : loopIndex % 6) == 2 ? crCode <<= 3
   : (loopIndex % 6 == 3) ? crCode *= 4 
   : loopIndex % 6 == 4 ? crCode *= 2
   : loopIndex % 6 == 5 ? crCode ^= 2

  arry.push(crCode);

  arry.join(-)
```

**Comment by Gujal00** [comment]
@sudovijay Changed yet again `scripts.js?v=1654657210`
I think we should leave this alone for a week or so until they settle down and then look at the code

**Comment by Gujal00** [comment]
@sudovijay Can you take a look at the current code and get the logic again please.

**Comment by sudovijay** [comment]
here ya go,

```
?v=1658530806 &key=EPvVAHpWuMbMDtFB

rc4key = rc4('GvewnmwTXw9E96ZT', video_id)

// custom base 64
$custom_code = 'e8RBZjCz64SfMJlvc1WboYAK2+9OwsQiVnGFt0ENudha5PrkIUgHT/x7L3XpqDmy';

$default = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

// base64 the video_id now

var arry = [];



for(var loopIndex=0; loopIndex < base64Key.length; loopIndex++)
{
 var crCode = base64Key.charCodeAt(loopIndex);

  loopIndex % 9 == 0 ? crCode -= 5
   : loopIndex % 9 == 1 ? crCode -= 5
   : loopIndex % 9) == 2 ? crCode <<= 5
   : (loopIndex % 9 == 3) ? crCode <<= 4
   : loopIndex % 9 == 4 ? crCode *= 5
   : loopIndex % 9 == 5 ? crCode += 6
 : loopIndex % 9 == 6 ? crCode ^= 2
 : loopIndex % 9 == 7 ? crCode ^= 2
: loopIndex % 9 == 8 ? crCode -= 4

  arry.push(crCode);
}

  arry.join(-)
```

**Comment by Gujal00** [comment]
Thanks @sudovijay looks like they are still changing the logic everyday.
The key was `key=FCQ0WTqbHgUX1Jm5` yesterday and today seems different. Will have to leave this alone for maybe longer. Thanks for the prompt reply

**Comment by Gujal00** [comment]
@sudovijay Are you de-obfuscating it by hand or by code. If by code, can you indicate approximately what you are looking for in code so that I can attempt similarly by code in Python (or js2py) for the plugin. Thanks

**Comment by sudovijay** [comment]
its by hand brother. didn't get time to actually automate this. everything is kinda obfuscated so ain't gonna be easy, i'll ping ya if i get any way around.

**Comment by jairoxyz** [comment]
Hi @sudovijay, I am trying to build a node module that could solve it for us but am stuck finding the part where the custom b64 function and the rc4 key is made. I can find and call the function making the final media but not the previous two steps needed. Any hint what to search for? Happy to chat in private somewhere else if you prefer.

**Pull request merged**
