### PR TITLE
 drkvid.py

### PR DESCRIPTION
**Pull request by Peter3344**
i try to add drkvid.site/embed but i cant add /play/

### CODE REVIEW

**Comment by Peter3344** [comment]
No this pr is working for embed- site  
But it’s not working for the website /play/

**Comment by Gujal00** [comment]
you always use the media id and pass embed url, so regardless of src url being /play/  the ger utl is always `'https://{host}/embed-{media_id}.html'` so should work

**Comment by Peter3344** [comment]
The pattern for the /play/ site is different on embed one /play/ use m3u8 playlist

**Comment by Gujal00** [comment]
Okay, so the media id is different for /play/ and embed-
/play/ has a pattern of `r'''file:\s*'(?P<url>[^']+)'''` but that is a relative url and doesnt include the base url, so cant be done in generic resolver, You would have to do a full Resolver to handle both cases

**Comment by Gujal00** [comment]
Sure, I will merge it for now, Thanks for the contribution
Will look at adding /play/ based on the html files that you have provided, and will ask you to test when done

**Pull request merged**
