### PR TITLE
Update voesx.py

### PR DESCRIPTION
**Pull request by k3ypusher**
Adds new domain 19turanosephantasia.com

### CODE REVIEW

**Review by shellc0de27 — CHANGES_REQUESTED** [review]
@k3ypusher You're missing the pipe in that regex. Please fix line 45 to
```python
r'745mingiestblissfully|19turanosephantasia|' \
```

**Comment by k3ypusher** [comment]
sorry, fixed it

**Review by shellc0de27 — APPROVED** [review]

**Comment by shellc0de27** [comment]
@k3ypusher Awesome thank you

**Comment by Gujal00** [comment]
Thanks for the PR and review

**Pull request merged**
