### PR TITLE
Update filemoon.py

### PR DESCRIPTION
**Pull request by DWH-WFC**

### CODE REVIEW

**Comment by shellc0de27** [comment]
what?

**Comment by kasi45** [comment]
I have just seen the PR and tested it (cinemathek.net)
the line setting referer to false is necessary

**Comment by shellc0de27** [comment]
I just grabbed a random one from that site and it played fine for me.

`SMR Link Tester: Link Resolved: |https://filemoon.sx/e/chuzlyqyht1z/|https://moon-storage-delivery-s23.filemoon.to/hls2/01/00812/,chuzlyqyht1z_n,chuzlyqyht1z_h,chuzlyqyht1z_x,lang/ger/chuzlyqyht1z_ger,lang/eng/chuzlyqyht1z_eng,lang/eng/chuzlyqyht1z_eng,.urlset/master.m3u8?t=TqIAbBoxITpGeY9VeMg4mMaB4nZVHr2i9XqlUr5R4Y8&s=1663420035&e=43200&f=4062000&srv=127.0.0.1&asn=209&sp=758&fr=chuzlyqyht1z|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F80.0.3987.132+Safari%2F537.36+OPR%2F67.0.3575.97&Referer=https%3A%2F%2Ffilemoon.sx%2F&Origin=https%3A%2F%2Ffilemoon.sx|`

Can you supply an embed that's not working?

**Comment by kasi45** [comment]
I can reproduce the error
the line setting referer to false is necessary
https://filmpalast.to/stream/yellowstone-s04e10

**without the line "referer=False"**

Unbenannt1

**with the line  "referer=False"**

Unbenannt

**the source code in the images is for debug only**

**Comment by shellc0de27** [comment]
@kasi45 Please post the filemoon url you are testing please and run it thru smr tester and your browser. When i go to that page that filemoon url is 404 and not even playable.

**Comment by shellc0de27** [comment]
Nevermind, got the media id from those pics.

**Comment by shellc0de27** [comment]
@kasi45 Thanks for your help identifying the url in question. Ive submitted a pull req with the only change needed.
@Gujal00 We can close this one.

**Comment by Gujal00** [comment]
Thanks @DWH-WFC @kasi45 @shellc0de27

**Pull request closed without merging**
