### PR TITLE
torbox: auto-pick largest video file

### PR DESCRIPTION
**Pull request by bleak-lodge**
Not sure why we should invoke user selection here, and not just pick the largest video file, like we do with the other debrid services for torrents.

### CODE REVIEW

**Comment by bleak-lodge** [comment]
Also tagging @pikdum for review

**Comment by pikdum** [comment]
If that's what all the other ones do, that's fine then.
Went with user selection since it was straightforward and seemed like a good default, especially for addons that haven't implemented the `return_all` flow.

**Comment by bleak-lodge** [comment]
This change doesn't affect the return_all flow, it's for single episodes/movies torrents.
But yeah, I understand that if an add-on is capable of scraping packs but doesn't properly handle them upon resolving (ie with the returnall flow) this could be handy.

**Review by pikdum — APPROVED** [review]
Tested these scenarios and everything looks good:
* only one video
* season pack, no prompt and largest video played automatically
* season pack with `return_all` flow and addon picking the right file

**Comment by bleak-lodge** [comment]
I don't know, maybe we should play with the `auto_pick` setting? But this is normally used for other reasons - multiple qualities for the same content.
@Gujal00 what do you think.

**Comment by Gujal00** [comment]
auto_pick is different, it reverse sorts on label and returns the url with the highest label (without the p at the end). Not suitable for this purpose.
Any addon implementing season pack need to have return_all processing to pick the correct episode, so is all good.
The changes you are proposing in this PR is consistent to how all the other debrid resolvers are written, so I would merge it as proposed

**Comment by pikdum** [comment]
I think it's good like this, nice to have plugins consistent even if the default behavior isn't my favorite.

**Pull request merged**
